include: package:flutter_lints/flutter.yaml
formatter:
  page_width: 80
  trailing_commas: preserve
linter:
  rules:
    await_only_futures: false
    avoid_print: false
    require_trailing_commas: true
    prefer_single_quotes: true
    cancel_subscriptions: true
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.gr.dart'
    - '**/*.freezed.dart'
  errors:
    unused_import: warning
    require_trailing_commas: warning
    invalid_annotation_target: ignore
