name: asset_code_generator
description: Generates Dart code based on the contents of the assets/ directory.
version: 1.0.0

environment:
  sdk: ^3.2.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
