// coverage:ignore-file
// ignore_for_file: type=lint, unused_field

// This file is generated by asset_code_generator
// Do not modify this file manually
// instead run `dart run asset_code_generator`

abstract final class AssetPaths {
  static const _$Images images = _$Images._();
  static const _$Icons icons = _$Icons._();
}

final class _$Images {
  const _$Images._();
  final String dennisaurus = 'assets/images/Dennisaurus.png';
  final String logoNoText = 'assets/images/logo_no_text.png';
}

final class _$Icons {
  const _$Icons._();
  final String vsc = 'assets/icons/vsc.png';
  final String ts = 'assets/icons/ts.png';
  final String xcode = 'assets/icons/xcode.png';
  final String flutter = 'assets/icons/flutter.png';
  final String firebase = 'assets/icons/firebase.png';
  final String android = 'assets/icons/android.png';
  final String androidStudio = 'assets/icons/android_studio.png';
  final String cloud = 'assets/icons/cloud.png';
  final String swift = 'assets/icons/swift.png';
  final String dart = 'assets/icons/dart.png';
  final String kotlin = 'assets/icons/kotlin.png';
}
